services:

    #
    # Providers
    #
    controller_extra.provider.entity:
        class: Mmoreram\ControllerExtraBundle\Provider\EntityProvider
        arguments:
            - "@service_container"
            - "@kernel"
            - "%controller_extra.entity_default_factory_method%"
            - "%controller_extra.entity_default_factory_static%"

    controller_extra.provider_collector:
        class: Mmoreram\ControllerExtraBundle\Provider\ProviderCollector

    controller_extra.provider.request_parameter:
        class: Mmoreram\ControllerExtraBundle\Provider\RequestParameterProvider
        arguments:
            - "@request_stack"
            - "%controller_extra.request%"
        tags:
            - { name: controller_extra.provider }
