services:

    #
    # Resolvers
    #
    controller_extra.resolver.log_annotation:
        class: Mmoreram\ControllerExtraBundle\Resolver\LogAnnotationResolver
        arguments:
            - "@logger"
            - "%controller_extra.log_default_level%"
            - "%controller_extra.log_default_execute%"
        tags:
            - { name: controller_extra.annotation_resolver }
