services:

    #
    # Resolvers
    #
    controller_extra.resolver.form_annotation:
        class: Mmoreram\ControllerExtraBundle\Resolver\FormAnnotationResolver
        arguments:
            - "@form.registry"
            - "@form.factory"
            - "%controller_extra.form_default_name%"
        tags:
            - { name: controller_extra.annotation_resolver }
