services:

    #
    # Resolvers
    #
    controller_extra.resolver.get_annotation:
        class: Mmoreram\ControllerExtraBundle\Resolver\GetAnnotationResolver
        tags:
            - { name: controller_extra.annotation_resolver }
