services:

    #
    # Resolvers
    #
    controller_extra.resolver.post_annotation:
        class: Mmoreram\ControllerExtraBundle\Resolver\PostAnnotationResolver
        tags:
            - { name: controller_extra.annotation_resolver }
