services:

    #
    # Resolvers
    #
    controller_extra.resolver.flush_annotation:
        class: Mmoreram\ControllerExtraBundle\Resolver\FlushAnnotationResolver
        arguments:
            - "@doctrine"
            - "%controller_extra.flush_default_manager%"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: controller_extra.annotation_resolver }
