services:

    #
    # Resolvers
    #
    controller_extra.resolver.paginator_annotation:
        class: Mmoreram\ControllerExtraBundle\Resolver\PaginatorAnnotationResolver
        arguments:
            - "@doctrine"
            - "@controller_extra.provider.entity"
            - "@controller_extra.provider_collector"
            - "@controller_extra.collector.paginator_evaluator"
            - "%controller_extra.paginator_default_name%"
            - "%controller_extra.paginator_default_page%"
            - "%controller_extra.paginator_default_limit_per_page%"
        tags:
            - { name: controller_extra.annotation_resolver }

    #
    # Evaluator collector
    #
    controller_extra.collector.paginator_evaluator:
        class: Mmoreram\ControllerExtraBundle\Resolver\Paginator\PaginatorEvaluatorCollector

    #
    # Evaluators
    #
    controller_extra.evaluator.paginator_innerjoins:
        class: Mmoreram\ControllerExtraBundle\Resolver\Paginator\PaginatorInnerJoinsEvaluator
        tags:
            - { name: controller_extra.paginator_evaluator }

    controller_extra.evaluator.paginator_leftjoins:
        class: Mmoreram\ControllerExtraBundle\Resolver\Paginator\PaginatorLeftJoinsEvaluator
        tags:
            - { name: controller_extra.paginator_evaluator }

    controller_extra.evaluator.paginator_wheres:
        class: Mmoreram\ControllerExtraBundle\Resolver\Paginator\PaginatorWheresEvaluator
        arguments:
            - "@controller_extra.provider.request_parameter"
        tags:
            - { name: controller_extra.paginator_evaluator }

    controller_extra.evaluator.paginator_orderby:
        class: Mmoreram\ControllerExtraBundle\Resolver\Paginator\PaginatorOrderByEvaluator
        arguments:
            - "@controller_extra.provider.request_parameter"
        tags:
            - { name: controller_extra.paginator_evaluator }

    controller_extra.evaluator.paginator_notnulls:
        class: Mmoreram\ControllerExtraBundle\Resolver\Paginator\PaginatorNotNullsEvaluator
        tags:
            - { name: controller_extra.paginator_evaluator }
