services:

    #
    # Resolvers
    #
    controller_extra.resolver.entity_annotation:
        class: Mmoreram\ControllerExtraBundle\Resolver\EntityAnnotationResolver
        arguments:
            - "@service_container"
            - "@doctrine"
            - "@controller_extra.provider.entity"
            - "@controller_extra.provider_collector"
            - "%controller_extra.entity_default_name%"
            - "%controller_extra.entity_default_persist%"
            - "%controller_extra.entity_fallback_mapping%"
        tags:
            - { name: controller_extra.annotation_resolver }
