services:

    #
    # Resolvers
    #
    controller_extra.resolver.json_resolver_annotation:
        class: Mmoreram\ControllerExtraBundle\Resolver\JsonResponseAnnotationResolver
        arguments:
            - "%controller_extra.json_response_default_status%"
            - "%controller_extra.json_response_default_error_status%"
            - "%controller_extra.json_response_default_headers%"
        tags:
            - { name: controller_extra.annotation_resolver }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: -128 }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -128 }
